name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Get current date
      id: date_time
      run: echo "::set-output name=date::$(date +'%Y%m%d%H%M')"

    - uses: actions/checkout@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
`
    - name: Build and push Nginx (web)
      run: docker buildx build . --platform linux/x86_64 --file nginx/web.Dockerfile --tag tommilew/sinatra-with-nginx:${{ steps.date_time.outputs.date }} --push
    
    - name: Build and push Sinatra (app)
      run: docker buildx build . --platform linux/x86_64 --file app.Dockerfile --tag tommilew/sinatra-with-nginx:${{ steps.date_time.outputs.date }} --push
